name: Cypress E2E Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    name: Run Cypress E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version
      - name: Start Docker environment
        run: docker compose -f cypress/docker/docker-compose.yml up -d
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/**/*.cy.ts" --browser chrome
      - name: Merge Mochawesome reports
        run: npm run report:all
      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/merged.html
